### ISSUE TITLE
contract call failure TypeError: can't access property "call", contract is undefined

### ISSUE THREAD

**Issue by Ash1shh** [adrianhajdin/project_crowdfunding#36]
contract call failure TypeError: can't access property "call", contract is undefined
    useContractWrite index-dd0e7329.esm.js:1174
    fn mutation.ts:177
    run retryer.ts:145
    createRetryer retryer.ts:201
    executeMutation mutation.ts:172
    execute mutation.ts:214

**Comment by VishalChauhan011** [comment]
is it fixed now ?

**Comment by thelastdemon1337** [comment]
I'm having the same issue, did you find any fix for this?

**Comment by alisonborba** [comment]
I've created an [MR-74](https://github.com/adrianhajdin/project_crowdfunding/pull/74) to fix it. Please take a look, test it on your environment and let me know if it solved your issue.

**Comment by ghousetazeem** [comment]
Hey, I am still getting the error, even after chanign the desired chain id to active chain and giving chainid properly. Do you have any solution for
